---
title: "Calculus Workshop 2024 Syllabus"
subtitle: "Bren MESM Orientation"
author: "Nathaniel Grimes"
format:
  pdf:
    include-in-header:
      text: |
        \addtokomafont{disposition}{\rmfamily}
editor: visual
---

Email: nggrimes\@ucsb.edu

Office: Bren Hall 3007

Location: Bren Hall 1414

## Course Objectives

Bren students come from all walks of life. Some incoming students might be twenty year career professionals in everything but math. Others might be right out of their math Bachelors degree armed with multivariate calculus and real analysis. This workshop is meant to get everyone to a sufficient level to excel in all the courses offered at Bren. Collaboration is essential during your MESM program. This workshop will build teams so that everyone can benefit from diverse backgrounds in both math and life. The primary workshop objectives are as follows:

-   Reinforce math skills used in Bren courses

-   Understand how math and calculus are used in Environmental Science

-   Help transition to graduate school life

-   Build collaborative environment

## Workshop design

New research has shown that active learning outside of traditional lecture formats boosts student engagement, understanding, and comfort.

We'll be using a Team Based Learning (TBL) environment. Students will be grouped into teams of 4-5. [Please take this survey](https://docs.google.com/forms/d/13qlU8WEgVMUxiuF9gezNgu5oAbgDX4zeN1QcjbZssfM/edit) so I can balance teams across math comfort, background, and when the last time you did a problem set. Teams will work and collaborate together throughout the workshop.

### Student Responsibilities

Students are responsible for showing up adequately prepared for each lecture by completing problem sets and watching pre-class videos posted on course website.

Students actively support and encourage teammates to improve learning for all. Students are encouraged to approach the instructor to help resolve conflicts if they cannot be resolved internally.

Students must be active participants within their team to deepen engagement.

### Class strucutre

Here is a sample framework each class will generally follow.

-   10 minutes team problem set debrief

-   10 minute class wide review

-   15-20 minute new instruction

-   10 minute Team assessment

-   5-10 minute break

-   20 minute instruction

-   10 minute Team assessment

-   15-20 minute Team environmental problem application

### Work outside class

Typically TBL environments consist of outside learning modules that students can walkthrough at their own pace. However, given the 8-5 schedule of orientation week and the far more important socializing that occurs after hours, we'll be dropping those elements. Instead, short problem sets no more than 8 questions will be given online. I will reference some specific Khan Academy or Paul's notes resource to help students prepare for the next day. But that will be the extent of outside work.

## Course Materials

Course materials will be accessible on the [course website](nggrimes.github.io/brencalculus). Videos, problem sets, answer keys, and slides will be hosted there. In addition, any code generated for the course will be hosted on the workshop public [github repo](https://github.com/nggrimes/bren-math-workshop). Coding is a skill that will be taught at Bren through ESM 206, data bootcamp, and ESM 244. Seeing more examples of codes always helps to understand how it works.

## Schedule and Topic Outline

Thursday September 19, 2024 **12:00 P.M. - 2:00 P.M.**: Introduction, Algebra and pre-calculus review, e.g. exponents and logarithms

Friday September 20, 2024 **9:00 A.M. - 11:00 A.M.**: Graphing, Limits, and Fundamentals of Calculus

Friday September 20, 2024 **12:00 P.M. - 2:00 P.M.**: Rules and Applications of derivatives

Monday September 23, 2024 **9:00 A.M. - 11:00 A.M.**: Integration

Tuesday September 24, 2024 **12:30 P.M. - 2:30 P.M.**: Differential Equations and Computational Calculus, i.e. let a computer do the work

## Grading and participation

This workshop is not mandatory, though highly encouraged. The team environment will deepen your own individual understanding even if you have a mastery of calculus as you will help your teammates along the way. Nothing will be graded, but each problem set will include immediate feedback and answer keys.

## Office Hours

I will be available following each class period to discuss anything, including topics beyond math. If you would like extra time to meet please email me to arrange a time.

## Extra Resources

It is impossible to cram 3 quarters of math into 5 days. Here is a brief list of external resources if you want to brush up on more math topics. This will be added to as resources are identified. If students find additional resources that are useful to them, please feel free to share!

[Khan Academy](https://www.khanacademy.org/) - Excellent collection of videos with in depth explanations on topics we covered here and beyond. The Calculus sections are particularly well thought out.

[Wolfram Mathematica](https://www.wolfram.com/mathematica/) - Online Equation solver. Can be cumbersome to use, but good to check solutions if worried about algebra mistakes.

[Paul's Math Notes](https://tutorial.math.lamar.edu/) Dr. Paul Dawkins at Lamar University has an awesome collection of all his lecture notes for his college level classes available here.
